export const CategoryLsit = [
    {
        id:1,
        image:require('../assets/categoryImages/vegies.png'),
        name:'vegies'
    },
    {
        id:2,
        image:require('../assets/categoryImages/cosmetics.png'),
        name:'cosmetics'
    },
    {
        id:3,
        image:require('../assets/categoryImages/food.png'),
        name:'food'
    },
    {
        id:4,
        image:require('../assets/categoryImages/snack.png'),
        name:'snack'
    },
    {
        id:5,
        image:require('../assets/categoryImages/vegies.png'),
        name:'vegies'
    },
    {
        id:6,
        image:require('../assets/categoryImages/food.png'),
        name:'food'
    },
    {
        id:7,
        image:require('../assets/categoryImages/food.png'),
        name:'food'
    },
    {
        id:8,
        image:require('../assets/categoryImages/snack.png'),
        name:'snack'
    },
    {
        id:9,
        image:require('../assets/categoryImages/vegies.png'),
        name:'vegies'
    },
    {
        id:10,
        image:require('../assets/categoryImages/food.png'),
        name:'food'
    },
    {
        id:11,
        image:require('../assets/categoryImages/snack.png'),
        name:'snack'
    },
    {
        id:12,
        image:require('../assets/categoryImages/vegies.png'),
        name:'vegies'
    },
    {
        id:13,
        image:require('../assets/categoryImages/food.png'),
        name:'food'
    },
    {
        id:14,
        image:require('../assets/categoryImages/snack.png'),
        name:'snack'
    },
    {
        id:15,
        image:require('../assets/categoryImages/vegies.png'),
        name:'vegies'
    },
    
    {
        id:16,
        image:require('../assets/categoryImages/vegies.png'),
        name:'vegies'
    },
]