export const food = [
    {
        id:1,
        image:require('../assets/food/apple.png'),
        name:'foodOne'
    },
    {
        id:2,
        image:require('../assets/food/blackberry.png'),
        name:'foodTwo'
    },
    {
        id:3,
        image:require('../assets/food/mango.png'),
        name:'foodThree'
    },
    {
        id:4,
        image:require('../assets/food/strawberry.png'),
        name:'foodOne'
    },
    {
        id:5,
        image:require('../assets/food/apple.png'),
        name:'foodOne'
    },
    {
        id:6,
        image:require('../assets/food/blackberry.png'),
        name:'foodOne'
    },
    {
        id:7,
        image:require('../assets/food/mango.png'),
        name:'foodOne'
    },
    {
        id:8,
        image:require('../assets/food/strawberry.png'),
        name:'foodOne'
    },
    {
        id:9,
        image:require('../assets/food/apple.png'),
        name:'foodOne'
    },
    {
        id:10,
        image:require('../assets/food/blackberry.png'),
        name:'foodOne'
    },
    {
        id:11,
        image:require('../assets/food/mango.png'),
        name:'foodOne'
    },
    {
        id:12,
        image:require('../assets/food/strawberry.png'),
        name:'foodOne'
    }
]

export const vegies = [
    {
        id:1,
        image:require('../assets/vegies/apple.png'),
        name:'vegiesOne'
    },
    {
        id:2,
        image:require('../assets/vegies/blackberry.png'),
        name:'vegiesTwo'
    },
    {
        id:3,
        image:require('../assets/vegies/mango.png'),
        name:'vegiesThree'
    },
    {
        id:4,
        image:require('../assets/vegies/strawberry.png'),
        name:'vegiesOne'
    },
    {
        id:5,
        image:require('../assets/vegies/apple.png'),
        name:'vegiesOne'
    },
    {
        id:6,
        image:require('../assets/vegies/blackberry.png'),
        name:'vegiesOne'
    },
    {
        id:7,
        image:require('../assets/vegies/mango.png'),
        name:'vegiesOne'
    },
    {
        id:8,
        image:require('../assets/vegies/strawberry.png'),
        name:'vegiesOne'
    },
    {
        id:9,
        image:require('../assets/vegies/apple.png'),
        name:'vegiesOne'
    },
    {
        id:10,
        image:require('../assets/vegies/blackberry.png'),
        name:'vegiesOne'
    },
    {
        id:11,
        image:require('../assets/vegies/mango.png'),
        name:'vegiesOne'
    },
    {
        id:12,
        image:require('../assets/vegies/strawberry.png'),
        name:'vegiesOne'
    }
]

export const cosmetics = [
    {
        id:1,
        image:require('../assets/vegies/apple.png'),
        name:'cosmeticsOne'
    },
    {
        id:2,
        image:require('../assets/vegies/blackberry.png'),
        name:'cosmeticsTwo'
    },
    {
        id:3,
        image:require('../assets/vegies/mango.png'),
        name:'cosmeticsThree'
    },
    {
        id:4,
        image:require('../assets/vegies/strawberry.png'),
        name:'cosmeticsOne'
    },
    {
        id:5,
        image:require('../assets/vegies/apple.png'),
        name:'cosmeticsOne'
    },
    {
        id:6,
        image:require('../assets/vegies/blackberry.png'),
        name:'cosmeticsOne'
    },
    {
        id:7,
        image:require('../assets/vegies/mango.png'),
        name:'cosmeticsOne'
    },
    {
        id:8,
        image:require('../assets/vegies/strawberry.png'),
        name:'cosmeticsOne'
    },
    {
        id:9,
        image:require('../assets/vegies/apple.png'),
        name:'cosmeticsOne'
    },
    {
        id:10,
        image:require('../assets/vegies/blackberry.png'),
        name:'cosmeticsOne'
    },
    {
        id:11,
        image:require('../assets/vegies/mango.png'),
        name:'cosmeticsOne'
    },
    {
        id:12,
        image:require('../assets/vegies/strawberry.png'),
        name:'cosmeticsOne'
    }
]

export const snack = [
    {
        id:1,
        image:require('../assets/vegies/apple.png'),
        name:'snackOne'
    },
    {
        id:2,
        image:require('../assets/vegies/blackberry.png'),
        name:'snackTwo'
    },
    {
        id:3,
        image:require('../assets/vegies/mango.png'),
        name:'snackThree'
    },
    {
        id:4,
        image:require('../assets/vegies/strawberry.png'),
        name:'snackOne'
    },
    {
        id:5,
        image:require('../assets/vegies/apple.png'),
        name:'snackOne'
    },
    {
        id:6,
        image:require('../assets/vegies/blackberry.png'),
        name:'snackOne'
    },
    {
        id:7,
        image:require('../assets/vegies/mango.png'),
        name:'snackOne'
    },
    {
        id:8,
        image:require('../assets/vegies/strawberry.png'),
        name:'snackOne'
    },
    {
        id:9,
        image:require('../assets/vegies/apple.png'),
        name:'snackOne'
    },
    {
        id:10,
        image:require('../assets/vegies/blackberry.png'),
        name:'snackOne'
    },
    {
        id:11,
        image:require('../assets/vegies/mango.png'),
        name:'snackOne'
    },
    {
        id:12,
        image:require('../assets/vegies/strawberry.png'),
        name:'snackOne'
    }
]